import Head from 'next/head'
import { gql, useQuery } from "@apollo/client";
import client from "../config/apollo-client.js";
import Restaurants from "../components/Restaurants.js";
import Category from '../components/Category.js';


export default function Home({ restaurants }) {
	// console.log(restaurants);
	//console.log(categories);
	return (
		<div>
			<Head>
				<title>Restaurants</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="p-12 max-w-md mx-auto">
				<h1 className="text-center text-6xl font-sans font-bold text-pink-500">
					Restaurants
				</h1>
			</div>
			{/* <Category /> */}
			<Restaurants restaurants={restaurants} />
		</div>
	);
}

export async function getStaticProps() {
	const { data } = await client.query({
		query: gql`
			query getRestaurants {
				restaurants {
					name
					description
					address
					categories {
						name
					}
					imagen {
						name
						url
					}
				}
			}
		`
	});

	return {
		props: {
			restaurants: data.restaurants,
		},
	};
}

// export async function getStaticPaths() {
// 	return {
		
// 		paths: [{ params: { id: "1" } }, { params: { id: "2" } }],
	
// 		fallback: true,
// 	};
// }

